projects:
  app:
    schemaPath: api/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4466
  database:
    schemaPath: api/generated/prisma.graphql
    extensions:
      prisma: api/database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: api/generated/prisma.ts
