version: "3.5"
services:
#  prisma:
#    image: prismagraphql/prisma:1.17
#    container_name: "prisma"
#    restart: always
#    depends_on:
#      - postgres
#      - redis
#    ports:
#      - "4466:4466"
#    environment:
#      PRISMA_CONFIG: |
#        port: 4466
#        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
#        # managementApiSecret: my-secret
#        databases:
#          default:
#            connector: postgres
#            host: postgres
#            port: '5432'
#            database: anime_index
#            user: "prisma-client"
#            password: "kawaii"
#            migrations: true
  postgres:
    image: postgres
    container_name: "postgres"
    ports:
      - "5000:5432"
    restart: always
    environment:
      POSTGRES_USER: "prisma-client"
      POSTGRES_PASSWORD: "kawaii"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: "redis"
#  solr:
#    container_name: "solr"
#    image: solr
#    ports:
#      - "8983:8983"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - core2:/opt/solr/server/solr/weebsearch

volumes:
  postgres:
#  core2:
