version: "3.5"
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha34
    container_name: hasura
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura-client:123@postgres/anime_index
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an access key
      # HASURA_GRAPHQL_ACCESS_KEY: mysecretaccesskey
  postgres:
    image: postgres
    container_name: "postgres"
    ports:
      - "5000:5432"
    restart: always
    environment:
      POSTGRES_USER: "prisma-client"
      POSTGRES_PASSWORD: "kawaii"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: "redis"
#  solr:
#    container_name: "solr"
#    image: solr
#    ports:
#      - "8983:8983"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - core2:/opt/solr/server/solr/weebsearch

volumes:
  postgres:
#  core2:
